/*
  Auto-generated by Spline
*/

import React from 'react'
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, Html } from '@react-three/drei'
import { LaptopLogo } from './LaptopLogo'


export const Laptop = ({ ...props }) => {
  const { nodes, materials } = useSpline('https://prod.spline.design/p-6Her3hHAitHm8E/scene.splinecode')

  return (
    <>
      <color attach="background" args={['#5e6063']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <group name="Computer">
            {/** Screen */}
            <mesh
              name="Rectangle 2"
              geometry={nodes['Rectangle 2'].geometry}
              material={materials['Rectangle 2 Material']}
              castShadow
              receiveShadow
              position={[0, 51.16, -44.62]}
              rotation={[-0.17, 0, 0]}
              scale={[0.61, 0.66, 0.66]}
            >
              {props.isLoggedIn && (
                <Html className="content" scale={[26.5, 24.5, 25]} position={[0, 0, 2]} transform occlude>
                  <div className="wrapper">
                    <p>Hello friend</p>
                  </div>
                </Html>
              )}
            </mesh>
            {/** Trackpad */}
            <mesh
              name="Rectangle 5"
              geometry={nodes['Rectangle 5'].geometry}
              material={materials.dark}
              castShadow
              receiveShadow
              position={[0, 4.61, 44.19]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.51, 0.55, 0.55]}
            />
            {/** Keyboard */}
            <mesh
              name="Rectangle 4"
              geometry={nodes['Rectangle 4'].geometry}
              material={materials.grey}
              castShadow
              receiveShadow
              position={[0, 6.72, 0.08]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.51, 0.55, 0.55]}
            />
            {/** Bottom part */}
            <mesh
              name="Rectangle 3"
              geometry={nodes['Rectangle 3'].geometry}
              material={materials.main}
              castShadow
              receiveShadow
              position={[0, 4.05, 13.16]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.61, 0.66, 0.66]}
            >
              <Html scale={[7, 7, 7]} position={[80, 50, 0]} rotation={[0, 50, 50]} transform>
                <div>
                  <p>See things backwards to move forward.</p>
                </div>
              </Html>
            </mesh>
            {/** Back part */}
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials.main}
              castShadow
              receiveShadow
              position={[0, 48.22, -47.93]}
              rotation={[-0.17, 0, 0]}
              scale={[0.61, 0.66, 0.66]}
            >
              <LaptopLogo generatedLogo={props.generatedLogo} />
            </mesh>
          </group>
          <OrthographicCamera
            name="Default Camera"
            makeDefault={true}
            zoom={1.85}
            far={50000}
            near={-50000}
            position={[404.43, 429.3, 807.55]}
            rotation={[-0.49, 0.42, 0.21]}
          >
            <directionalLight
              name="Default Directional Light"
              intensity={0.75}
              shadow-mapSize-width={1024}
              shadow-mapSize-height={1024}
              shadow-camera-near={-10000}
              shadow-camera-far={100000}
              position={[850000, 1300000, 1000000]}
            />
          </OrthographicCamera>
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
          />
        </scene>
      </group>
    </>
  )
}
